// Generated by CoffeeScript 1.9.3
(function() {
  var Tail, app, connect, express, fileName, http, io, server, socketio, tail;

  express = require('express');

  connect = require('connect');

  http = require('http');

  socketio = require('socket.io');

  Tail = require('tail').Tail;

  app = express();

  server = http.createServer(app).listen(9099);

  io = socketio.listen(server);

  app.set('view engine', 'jade');

  app.get('/', function(req, res) {
    res.render('index', {});
  });

  console.log("Server listening on port 9099...");

  fileName = '/var/log/syslog';

  tail = new Tail(fileName);

  tail.on('line', function(data) {
    return io.sockets.emit('new-data', {
      channel: 'stdout',
      value: data
    });
  });

  io.sockets.on('connection', function(socket) {
    return socket.emit('new-data', {
      channel: 'stdout',
      value: "tail file " + fileName
    });
  });

}).call(this);
